credentials:
  usernames:
    ali:
      name: Ali Khan
      password: hashed_password_here
    sara:
      name: Sara Ahmed
      password: hashed_password_here
cookie:
  expiry_days: 1
  key: auth
  name: my_app